### ISSUE TITLE
Insufficient Data

### ISSUE THREAD

**Issue by gauravchakrabarty** [cu-esiil-edu/2024-data-short-course#59]
@nquarder and @eculler 

I tried the assignment with locations Bangalore, Amritsar, and Alwar. However, later I found in all three places there was insufficient data. 

![Station Detail](https://github.com/cu-esiil-edu/2024-data-short-course/assets/8917893/70ae6305-7c0b-482c-b83d-c6c1f71b2842)
![code2_df](https://github.com/cu-esiil-edu/2024-data-short-course/assets/8917893/89c9c20f-dcb9-4598-a997-068d574fe656)
![Graph1](https://github.com/cu-esiil-edu/2024-data-short-course/assets/8917893/cf746cc3-06e8-43ff-a127-4759478d4c43)

Looks like I need to check stations from outside India.

**Comment by nquarder** [comment]
Hi @gauravchakrabarty  - 

Good question and one you should also post to the discussions (https://github.com/cu-esiil-edu/2024-data-short-course/discussions) rather than issues. I think you should also see this discussion from yesterday with @oye-bobs where we address a similar question (https://github.com/cu-esiil-edu/2024-data-short-course/discussions/56). 

I found the station you are looking at and think you should try replacing `TOBS` to `TAVG,TMIN,TMAX` in your API call and see what that does. It looks like those variables are available for that site going back to the 1970s so you will have sufficient data to look at trends.

![Screen Shot 2024-04-21 at 4 46 15 PM](https://github.com/cu-esiil-edu/2024-data-short-course/assets/16786791/0f467e51-2e22-4182-b7b9-077bb9341f76)


Hope this helps and good work on this assignment so far. - NQ

**Comment by gauravchakrabarty** [comment]
> Hi @gauravchakrabarty - 
> 
> Good question and one you should also post to the discussions (https://github.com/cu-esiil-edu/2024-data-short-course/discussions) rather than issues. I think you should also see this discussion from yesterday with @oye-bobs where we address a similar question ([https://github.com/cu-esiil-edu/2024-data-short-course/discussions/56). ](https://github.com/cu-esiil-edu/2024-data-short-course/discussions/56).%C2%A0)
> 
> I found the station you are looking at and think you should try replacing `TOBS` to `TAVG,TMIN,TMAX` in your API call and see what that does. It looks like those variables are available for that site going back to the 1970s so you will have sufficient data to look at trends.
> 
> ![Screen Shot 2024-04-21 at 4 46 15 PM](https://private-user-images.githubusercontent.com/16786791/324290138-0f467e51-2e22-4182-b7b9-077bb9341f76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDA5NjQsIm5iZiI6MTcxMzc0MDY2NCwicGF0aCI6Ii8xNjc4Njc5MS8zMjQyOTAxMzgtMGY0NjdlNTEtMmUyMi00MTgyLWI3YjktMDc3YmI5MzQxZjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIzMDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0N2M4YTM4NWJhNjU0MGIyM2U2ZTg1YzBlMGRiN2NiZjM4MmZlODVkZWY5OTlmODU1MjA3NjM0MWZjMjFmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMHvvp19aNTVbxp5zpKcPtoJ2NrTfUOF6AOxLRKIGMY)
> 
> Hope this helps and good work on this assignment so far. - NQ

Sir,
I have downloaded the three data files. The temperature data is missing for all three stations.
[daily-summaries-2024-04-21T17-29-07.csv](https://github.com/cu-esiil-edu/2024-data-short-course/files/15055325/daily-summaries-2024-04-21T17-29-07.csv)
[daily-summaries-2024-04-21T19-02-34.csv](https://github.com/cu-esiil-edu/2024-data-short-course/files/15055326/daily-summaries-2024-04-21T19-02-34.csv)
.
[daily-summaries-2024-04-21T16-42-50.csv](https://github.com/cu-esiil-edu/2024-data-short-course/files/15055324/daily-summaries-2024-04-21T16-42-50.csv)

**Comment by nquarder** [comment]
Yes @gauravchakrabarty it appears that you need to change `TOBS` to `TAVG, TMAX, TMIN' in your API call (the URL you create to request your data). Are you able to share that so we can see what data you are requesting?
